### ISSUE TITLE
EL7 cvmfs Python/v3.6.8-2 : pip3 breaks because libffi.so.5 not found

### ISSUE THREAD

**Issue by adriansev** [alisw/alidist#1772]
trying to use pip3 from dependencies of vAN-20190808_ROOT6-1 i get   
```
which python3
alias python3='python3.6'
        /cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/bin/python3.6

pip3 list
Traceback (most recent call last):
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/bin/pip3.6", line 7, in <module>
    from pip._internal import main
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/lib/python/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/lib/python/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/lib/python/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/lib/python/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/lib/python/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/lib/python/site-packages/pip/_internal/cli/base_command.py", line 18, in <module>
    from pip._internal.download import PipSession
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/lib/python/site-packages/pip/_internal/download.py", line 38, in <module>
    from pip._internal.utils.glibc import libc_ver
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/lib/python/site-packages/pip/_internal/utils/glibc.py", line 3, in <module>
    import ctypes
  File "/cvmfs/alice.cern.ch/el6-x86_64/Packages/Python/v3.6.8-2/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.5: cannot open shared object file: No such file or directory

```

**Comment by ktf** [comment]
I think this is long solved. Closing.
