### ISSUE TITLE
Wrong Python used by PyROOT

### ISSUE THREAD

**Issue by dberzano** [alisw/alidist#468]
As reported by some users:

```
[AliPhysics/vAN-20160627-1] ~ > virtualenv virtualenvs/testenv
[AliPhysics/vAN-20160627-1] ~ > echo "${ROOTSYS}/lib:${PYTHONPATH}"
/cvmfs/alice.cern.ch/x86_64-2.6-gnu-4.1.2/Packages/ROOT/v5-34-30-alice5-alice-1/lib:
[AliPhysics/vAN-20160627-1] ~ > export PYTHONPATH="${ROOTSYS}/lib:${PYTHONPATH}"
[AliPhysics/vAN-20160627-1] ~ > source virtualenvs/testenv/bin/activate
(testenv)[AliPhysics/vAN-20160627-1] ~ > python

Python 2.6.6 (r266:84292, Jul 23 2015, 00:03:09)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import ROOT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/alice.cern.ch/x86_64-2.6-gnu-4.1.2/Packages/ROOT/v5-34-30-alice5-alice-1/lib/ROOT.py", line 103, in <module>
    import libPyROOT as _root
ImportError: libpython2.4.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by dberzano** [comment]
There are a couple of issues here.

* ROOT detects Python 2.4 and compiles against it, despite our SLC5 environment used for the builds has Python 2.6 as default. We should make ROOT point to the one we want.
* We should find a better way to bring our own Python on the Grid.

**Comment by ktf** [comment]
Probably not an issue anymore.
